main: "cc.dreamcode.msgplugin.MsgPlugin"
version: "1.0-InDEV"
name: "Dream-MsgPlugin"
description: "Dream-MsgPlugin plugin written by dreamcode.cc"
website: "https://dreamcode.cc"
author: "n4a_"
api-version: 1.13